### ISSUE TITLE
trailing slash needs removing 

### ISSUE THREAD

**Issue by wuxmedia** [wuxmedia/cs#1]
this:
cs http://wuxmedia.com/
breaks. 
This:
cs http://wuxmedia.com
Works - trailing slash could do with being cut off

**Comment by fleetcaptain** [comment]
Is this issue still open? I just cloned the repository and attempted to reproduce but it seemed to work

**Comment by wuxmedia** [comment]
I get this:
`wux@nargothrond:~/cs$ ./cs.sh http://wuxmedia.com/
NAME SERVERS: 
HOST:
Host wuxmedia.com/ not found: 3(NXDOMAIN)
REVERSE LOOKUP:
`

**Comment by wuxmedia** [comment]
ahh damn - you're right I fixed it already :/

**Comment by fleetcaptain** [comment]
No worries!
